openapi: 3.0.0
info:
  title: Isagog Documental Question Answering
  version: 1.0.0
  description: >-
    Documental Question Answering Server. Receives questions, searches
    document collections for answers, and returns them back.
  contact:
    email: api@isagog.com
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: "http://localhost"
    variables:
      port:
        default: "3300"
      basePath:
        default: "/v1"
paths:
  /AskQuestion:
    post:
      summary: Search for answers to a natural language question
      parameters:
        - in : query
          name: text
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Found list of candidate answers
          content:
            application/json:
              schema:
                description: a ranked list of candidate answers
                type: array
                items:
                  $ref: "#/components/schemas/CandidateAnswer"
        '500':
          description: Answer not found
components:
  schemas:
    CandidateAnswer:
      description: a candidate answer
      type: object
      required:
        - text
        - docref
        - score      
      properties:
        text:
          description: Answer Text
          type: string
        docref:
          description: Pathname of the Source Document
          type: string
        score:
          description: Confidence Score for the Answer
          type: number
          format: float
